AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'frab-api

  Sample SAM Template for frab-api

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  BookingQueueExpiration:
    Type: Number
    Default: 120
  DefaultRegion:
    Type: String
    Default: ap-southeast-1
Resources:
  BookingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: BookingQueue
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 5
      MessageRetentionPeriod: 120
  GetRideFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://frab-api-artifact/a37e6ba30bfde883a634b8900a0629eb
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        FrabApi:
          Type: Api
          Properties:
            Path: /rides/{rideId}
            Method: get
      Environment:
        Variables:
          DEFAULT_REGION:
            Ref: DefaultRegion
          RIDES_TABLE:
            Fn::Select:
            - 1
            - Fn::Split:
              - /
              - Fn::GetAtt:
                - RidesTable
                - Arn
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: RidesTable
  BookRideFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://frab-api-artifact/8ee26b80d5d60aca1d85ca253b5375e0
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        FrabApi:
          Type: Api
          Properties:
            Path: /rides
            Method: post
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: RidesTable
      - SQSSendMessagePolicy:
          QueueName:
            Fn::GetAtt:
            - BookingQueue
            - QueueName
      Environment:
        Variables:
          DEFAULT_REGION:
            Ref: DefaultRegion
          BOOKING_QUEUE:
            Ref: BookingQueue
          RIDES_TABLE:
            Fn::Select:
            - 1
            - Fn::Split:
              - /
              - Fn::GetAtt:
                - RidesTable
                - Arn
  RidesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: ride_id
        AttributeType: S
      KeySchema:
      - AttributeName: ride_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  FrabApi:
    Description: API Gateway endpoint URL for Prod stage for Book Ride function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/rides/
  BookRideFunction:
    Description: BookRideFunction Lambda Function ARN
    Value:
      Fn::GetAtt:
      - BookRideFunction
      - Arn
  BookRideFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - BookRideFunctionRole
      - Arn
